/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "D:\Mustafa\MBEngine\MBEngine\RemotingService\protocol\protos\headprotocol_onc.h"

bool_t
xdr_array (XDR *xdrs, array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->arr_val, 1000000,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
